# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Gandazgul.RunWield
PackageVersion: 0.11.3
InstallerLocale: en-US
InstallerType: zip
Commands:
- wld
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Git.Git
Installers:
- Architecture: x64
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: wld.exe
    PortableCommandAlias: wld
  InstallerUrl: https://github.com/gandazgul/runwield/releases/download/v0.11.3/wld-v0.11.3-windows-x64.zip
  InstallerSha256: 4692608465A384CE14820137F25A3CC1F4A3C27B1CD599BE3E4B9306B19D1CE9
  ArchiveBinariesDependOnPath: true
ManifestType: installer
ManifestVersion: 1.10.0
