# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Gandazgul.RunWield
PackageVersion: 0.11.5
InstallerLocale: en-US
InstallerType: zip
Commands:
- wld
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Git.Git
Installers:
- Architecture: x64
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: wld.exe
    PortableCommandAlias: wld
  InstallerUrl: https://github.com/gandazgul/runwield/releases/download/v0.11.5/wld-v0.11.5-windows-x64.zip
  InstallerSha256: 8348109E0777417CB4EE1FB369F36FC2100F6C85B3AED275CC0642D2070B41CF
  ArchiveBinariesDependOnPath: true
ManifestType: installer
ManifestVersion: 1.10.0
